# Generated by Django 3.1.5 on 2021-02-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('flavour', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.CharField(max_length=20)),
                ('Status', models.CharField(default='Available', max_length=15)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
