# Generated by Django 3.1.5 on 2021-02-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Order_details', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('bill', models.DecimalField(decimal_places=2, max_digits=4)),
                ('deliveryStatus', models.CharField(default='Reviewing Your order', max_length=50)),
                ('deliveryboysDetails', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillAmount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('paymentMethod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=25)),
                ('flavour', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.CharField(max_length=20)),
                ('Status', models.CharField(default='Available', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=2)),
            ],
        ),
    ]
