# Generated by Django 3.1.5 on 2021-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='order_details',
            old_name='qty',
            new_name='total_qty',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='name',
        ),
        migrations.AddField(
            model_name='order_details',
            name='u_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
