# Generated by Django 3.1.5 on 2021-02-24 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUserModel',
            new_name='User_Details',
        ),
    ]
