# Generated by Django 3.1.5 on 2021-03-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Feedback',
            field=models.CharField(max_length=255),
        ),
    ]
